### PR TITLE
Fail base64 validation if unrecognized characters are found

### LINKED ISSUE #4: Base64BinaryType validation is (maybe) not compliant.
Hi! We recently found ourselves on a weird situation where strings like `!Y@Q#=$=^` validated as base64 without issues. We understand that these strings are valid per [RFC2045](https://www.ietf.org/rfc/rfc2045.txt) but ended up puzzled on the XML Schema description for [`base64Binary`](https://www.w3.org/TR/xmlschema-2/#base64Binary).

Let me quote both specifications:

### Relevant code
[Base64BinaryType.java:119](https://github.com/xmlark/msv/blob/main/xsdlib/src/main/java/com/sun/msv/datatype/xsd/Base64BinaryType.java#L119-L158)
```java
/**
 * computes the length of binary data.
 * 
 * This function also performs format check.
 * @return    -1        if format is illegal.
 * 
 */
private static int calcLength( final char[] buf ) {
    final int len = buf.length;
    int base64count=0, paddingCount=0;
    int i;

    for( i=0; i<len; i++ ) {
        if( buf[i]=='=' )    // decodeMap['=']!=-1, so we have to check this first.
            break;
        if( buf[i]>=256 )
            return -1;      // incorrect character
        if( decodeMap[buf[i]]!=-1 )
            base64count++;
    }

    // once we saw '=', nothing but '=' can be appeared.
    for( ; i<len; i++ ) {
        if( buf[i]=='=' ) {
            paddingCount++;
            continue;
        }
        if( buf[i]>=256 )
            return -1;      // incorrect character
        if( decodeMap[buf[i]]!=-1 )
            return -1;
    }

    // no more than two paddings are allowed.
    if( paddingCount > 2 )        return -1;
    // characters must be a multiple of 4.
    if( (base64count+paddingCount)%4 != 0 )    return -1;

    return ((base64count+paddingCount)/4)*3-paddingCount;
}
```

I do think that some facility for requesting stricter validation is needed. On the spec-compliance side of things I don't know how to position myself given these conflicting accounts (XML Schema depends on the RFC).

### PR DESCRIPTION
**Pull request by iglosiggio**
This should fix #4. I've changed the conformance tests accordingly but these aren't enabled by default during compilation (and some are failing).

### CODE REVIEW

File: xsdlib/src/main/java/com/sun/msv/datatype/xsd/Base64BinaryType.java [hunk 1]
```diff
@@ -226,6 +224,10 @@ public String convertToLexicalValue( Object value, SerializationContext context
         return serializeJavaObject( ((BinaryValueType)value).rawData, context );
     }
 
+    private static boolean isXMLSpace(char c) {
+        return c == ' ' || c == '\r' || c == '\n' || c == '\t';
+    }
```
Comment (iglosiggio) [inline xsdlib/src/main/java/com/sun/msv/datatype/xsd/Base64BinaryType.java:230]:
```suggestion
    private static boolean isXMLSpace(char c) {
        // Per https://www.w3.org/TR/xml/#NT-S
        return c == ' ' || c == '\r' || c == '\n' || c == '\t';
    }
```

**Comment by svanteschubert** [comment]
@iglosiggio A thousand thanks for this patch! Allow me to fix the enabling of the tests first, I was not aware!
I realized that when I move the non-java files from, for example
xsdlib/src/test/java
to
xsdlib/src/test/resources
they are automatically copied by Maven during build and in this case, the main method finds the test XML with its class loader!

PS: I beg your pardon, that I have overseen the patches in my email (they are not yet in my "primary" folder of GMail, but in "updates" with commercials) I added an item to my ToDo list to mark GitHub notifications as important!

**Comment by svanteschubert** [comment]
For instance, for XSDLIB Git would show the following file movements:
R  java/com/sun/msv/datatype/xsd/conformance/DataTypeTest.xml -> resources/com/sun/msv/datatype/xsd/conformance/DataTypeTest.xml
R  java/com/sun/msv/datatype/xsd/conformance/DerivationTest.xml -> resources/com/sun/msv/datatype/xsd/conformance/DerivationTest.xml
R  java/com/sun/msv/datatype/xsd/conformance/package.html -> resources/com/sun/msv/datatype/xsd/conformance/package.html

**Comment by svanteschubert** [comment]
After moving the XML files from src/test/java to src/test/resources they will appear in target test class directory 
xsdlib/target/test-classes and are accessible by the class loader:

Earlier you will find only class files:
find . -name *.class -type f
later you will find other files:
find . -not -name *.class -type f

**Comment by svanteschubert** [comment]
@iglosiggio Could you please try to update your branch/pull request? 
I have moved the XML file that you have changed and GitHub is not automatically rebasing the changes. 
Otherwise, I will try in the following days!

PS: When you test, the error message "CatalogManager.properties: catalogs not found." happened earlier as well, therefore I still think the *.properties belong to the src/main/resources directory.

**Comment by svanteschubert** [comment]
As the update of a pull request not by the owner is not intuitively documented (uncertain this is possible at all at GitHub), I have created a new rebased branch, where your issues for #4 are within: 
https://github.com/xmlark/msv/tree/strict-base64-validation
Could you give the **branch strict-base64-validation** a try, which are your two commits rebased on top of the main branch!

What concerns me is that there are some errors thrown in the newly activated test, although it seems not related to your change, but regarding data types. 

Can you or anyone dive there a bit deeper?

I would like to do a new MSV release soon, but the new errors do not look so good (even if the test had been disabled earlier) ;-)

Thank you in advance,
Svante

PS: I renamed the test class back "removing again its new suffix 'Test'", as I remembered that explicit names could be added to the pom.xml of Maven to be executed by the Surefire test plugin!

**Comment by svanteschubert** [comment]
@iglosiggio I just read beyond the box, that I simply would have cloned your repo and made a pull request there, to update this pull request! Now I know for the next time! :-)

**Comment by iglosiggio** [comment]
Thanks for all the comments @svanteschubert! I'll look into this tomorrow 😅

**Comment by iglosiggio** [comment]
@svanteschubert just checked on our sw and it worked perfectly! I've just reseted my branch personal so it points at your rebase (feel free to merge either one).

**Comment by svanteschubert** [comment]
@iglosiggio Thanks a lot, Ignacio!
The only thing that worries me is the old tests that is now running and providing some errors:
************* error *************
type name            : gDay
tested instance      : " ---00 "
supposed to be valid : false
verify method        : true
createValue method   : true
createJavaObj method : true
diagnose method      : true
JavaObjectType       : class java.util.GregorianCalendar
expected Type        : class java.util.Calendar
serializeJavaObject  : ---31
convertToLexical     : ---00

see https://github.com/xmlark/msv/blob/strict-base64-validation/xsdlib/src/test/java/com/sun/msv/datatype/xsd/conformance/TestDriver.java#L70

Which I have not attached to failing a JUnit test (the build would break).
Likely those are "just" false positives, but I am uncertain and have little time to debug.
As you have adopted this test - at least the XML and by this awaken the sleeping docs ;-) - could you provide some feedback on this? Perhaps fix those?

Thanks in advance,
Svante

**Comment by svanteschubert** [comment]
I have added some JUnit Assert.fail(..) to the tests to make our problem a little more obvious:
https://github.com/xmlark/msv/compare/strict-base64-validation...iglosiggio:msv:strict-base64-validation
and duplicated it on our branch here:
https://github.com/xmlark/msv/commit/2f3c720f4fb1b9c8850a2cc70d394bbea9684456

Earlier these tests were not executed, I was not aware of them until you fixed one. 
Which is good! I enabled them now - we might disable them again, but I would feel safer if someone could take a look at it before a release... (I am sorry, I am drowning in deadlines...)

**Comment by mistmist** [comment]
i did try to fix the test, it's quite confusing, i found 2 bugs, fixed one of them, disabled lots of test inputs, ran out of time...

**Comment by svanteschubert** [comment]
@iglosiggio @mistmist Does anyone have time to take a look at this and finish the PR?

**Comment by svanteschubert** [comment]
@iglosiggio @mistmist I will give it a try, starting to enable all tests again, so the need for a fix is obvious by the failing tests... ;-)

**Comment by svanteschubert** [comment]
I first enabled all the failing tests and test inputs, then disabled one cause, one after the other.
In the end, all tests are now working. Could you please review these changes?

Sometimes, I had to make design decisions. I initially allowed test values that contained an f/F to be mapped to xsd:float value, but removed this afterwards. Therefore, I am curious about your comments.

Tried to make the commit messages as verbose as possible so it is easier to review - instead of creating a GitHub issue for every fix on the build (avoiding overhead).

At least we have some progress now! :-)

**Comment by svanteschubert** [comment]
PS: I initially pushed to msv and then realised we were working on the GitHub branch of iglosiggio, so I pushed again there. Sorry for the confusion...

**Comment by iglosiggio** [comment]
> I first enabled all the failing tests and test inputs, then disabled one cause, one after the other. In the end, all tests are now working. Could you please review these changes?

I took an cursory review of the changes and everything looks nice! (Some of the parsing feels a bit convoluted but that's parsing heh).

I'll go commit-by-commit later (mainly to properly understand the test changes).

File: xsdlib/src/main/java/com/sun/msv/datatype/xsd/datetime/AbstractCalendarParser.java [hunk 2]
```diff
@@ -233,5 +237,5 @@ private static boolean isDigit(char ch) {
     protected abstract void setHours(int i);
     protected abstract void setDay(int i);
     protected abstract void setMonth(int i);
-    protected abstract void setYear(int i);
+    protected abstract void setYear(BigInteger i);
```
Comment (mistmist) [inline xsdlib/src/main/java/com/sun/msv/datatype/xsd/datetime/AbstractCalendarParser.java:240]: well this is some overengineering...

File: xsdlib/src/test/resources/com/sun/msv/datatype/xsd/conformance/DataTypeTest.xml [hunk 3]
```diff
@@ -1081,7 +1081,7 @@
 		</combination>
 		<combination mode="or">
 			<facet answer=		"...... .oooo o.... .." name="enumeration" value="+0" />
-			<facet answer=		"...... o.... o.... .." name="enumeration" value="-0" />
+			<facet answer=		"...... o.... ..... .." name="enumeration" value="-0" />
```
Comment (mistmist) [inline xsdlib/src/test/resources/com/sun/msv/datatype/xsd/conformance/DataTypeTest.xml:1084]: well this just reverts half of previous commit

**Review by mistmist — APPROVED** [review]

**Comment by mistmist** [comment]
i want to apologize to @iglosiggio - i think what happened here is that Svante had the idea that we should revive this old unit test, i had 90 minutes left on my last day before vacation, so let's give it a try ... then after 3 hours i gave up, pushed the work-in-progress, went on vacation and completely forgot about this.

we should have just merged your fix without a test, and left that test suite as future work...

**Comment by svanteschubert** [comment]
@iglosiggio, if you find related later issues, please do not hesitate to send a pull request

At least the tests are enabled, and we have some safety net.
